name: project_android
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  awesome_drawer_bar: ^1.2.0
  shared_preferences: ^2.0.6
  buttons_tabbar: ^1.3.10
  image_picker: ^0.8.4+8
  flutter:
    sdk: flutter
  flutter_calendar_week: ^2.0.0
  flutter_slider_drawer: ^2.1.3
  font_awesome_flutter: ^10.7.0
  horizontal_week_calendar: ^0.0.16
  salomon_bottom_bar: ^3.3.2
  table_calendar: ^3.1.1
  unicons: ^2.1.1
  provider: ^6.0.0
  intl: ^0.19.0
  flutter_carousel_widget: ^2.2.0
  dio: ^5.5.0+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo2.png
    - assets/images/
    - assets/files/
